### ISSUE TITLE
GleapFeedbackButton updateContraintForOrientation causes crash

### ISSUE THREAD

**Issue by kkarakamis** [GleapSDK/Gleap-iOS-SDK#3] opened 2023-11-02 11:09 UTC
In our project, Gleap Feedback Button set hidden in didFinishLaunchWithOptions. 
Sometimes we are getting crash reports about updateContraintForOrientation for feedback button.
<img width="383" alt="Screenshot 2023-11-02 at 14 08 57" src="https://github.com/GleapSDK/Gleap-iOS-SDK/assets/32245278/c6fcf362-4a14-42fd-974f-8260a9a718db">

**Comment by boehlerlukas** [comment] 2023-11-03 08:59
Hey @kkarakamis ,

Thanks a lot for sharing! Does this happen with the latest version as well? This issue was there in an older version, but the most recent version should actually contain a fix :)

Best,
Lukas

**Comment by kkarakamis** [comment] 2023-11-03 09:29
Hi @boehlerlukas 

Great to hear that. We are currently using v11.2.1. And today I'll update it to v12. 

Thanks for quick response.

**Comment by boehlerlukas** [comment] 2023-11-03 11:09
@kkarakamis let me know if this does not fix the issue. Happy to take another look asap.

**Comment by kkarakamis** [comment] 2023-11-19 21:05
Hi @boehlerlukas,
We updated gleap sdk to the latest version(v12.1.0) but still have this issue. 

You can check part of crash log in here
`Thread 0 name:
Thread 0 Crashed:
0   libobjc.A.dylib               	0x000000019c572bcc realizeClassMaybeSwiftMaybeRelock(objc_class*, locker_mixin<lockdebug::lock_mixin<objc_lock_base_t> >&, bool) + 148 (objc-runtime-new.mm:3114)
1   libobjc.A.dylib               	0x000000019c571bb0 lookUpImpOrForward + 880 (objc-runtime-new.mm:7367)
2   libobjc.A.dylib               	0x000000019c56ccc4 _objc_msgSend_uncached + 68 (:-1)
3   CoreAutoLayout                	0x00000001c473821c +[NSLayoutConstraint _addOrRemoveConstraints:activate:] + 236 (NSLayoutConstraint.m:2091)
4   App                       	0x00000001041dcf6c -[GleapFeedbackButton updateConstraintsForOrientation] + 996 (GleapFeedbackButton.m:385)
5   CoreFoundation                	0x00000001a41b34c8 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 148 (CFNotificationCenter.c:700)
6   CoreFoundation                	0x00000001a41b2e90 ___CFXRegistrationPost_block_invoke + 88 (CFNotificationCenter.c:193)
7   CoreFoundation                	0x00000001a41b2dd8 _CFXRegistrationPost + 440 (CFNotificationCenter.c:221)
8   CoreFoundation                	0x00000001a41b2328 _CFXNotificationPost + 724 (CFNotificationCenter.c:1245)
9   Foundation                    	0x00000001a314e864 -[NSNotificationCenter postNotificationName:object:userInfo:] + 92 (NSNotification.m:531)
10  UIKitCore                     	0x00000001a6535068 -[UIDevice setOrientation:animated:] + 252 (UIDevice.m:1002)
11  GAXClient                     	0x0000000102833e54 -[GAXUIDeviceOverride setOrientation:animated:] + 112 (GAXClientOverrides.m:854)
12  UIKitCore                     	0x00000001a69a3df4 __134-[_UIWindowSceneDeviceOrientationSettingsDiffAction _updateDeviceOrientationWithSettingObserverContext:windowScene:transitionContext:]_block_invoke + 104 (_UIWindowSceneDeviceOrientationSettingsDiffAction.m:56)
13  UIKitCore                     	0x00000001a64e0930 +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:fromCurrentState:actions:completion:] + 736 (BSAnimationSettings+UIKit.m:54)
14  UIKitCore                     	0x00000001a64e01b8 _UISceneSettingsDiffActionPerformChangesWithTransitionContextAndCompletion + 224 (_UISceneSettingsDiffAction.m:27)
15  UIKitCore                     	0x00000001a66537a8 -[_UIWindowSceneDeviceOrientationSettingsDiffAction _updateDeviceOrientationWithSettingObserverContext:windowScene:transitionContext:] + 204 (_UIWindowSceneDeviceOrientationSettingsDiffAction.m:52)
16  UIKitCore                     	0x00000001a64e2408 -[_UIWindowSceneDeviceOrientationSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:] + 168 (_UIWindowSceneDeviceOrientationSettingsDiffAction.m:43)
17  UIKitCore                     	0x00000001a6863620 __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke.225 + 612 (UIScene.m:2053)
18  UIKitCore                     	0x00000001a64defec -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:] + 216 (UIScene.m:1722)
19  UIKitCore                     	0x00000001a64dee5c -[UIScene scene:didUpdateWithDiff:transitionContext:completion:] + 244 (UIScene.m:2012)
20  UIKitCore                     	0x00000001a64dec9c -[UIApplicationSceneClientAgent scene:handleEvent:withCompletion:] + 336 (UIApplicationSceneClientAgent.m:86)
21  FrontBoardServices            	0x00000001bc4225b4 -[FBSScene updater:didUpdateSettings:withDiff:transitionContext:completion:] + 660 (FBSScene.m:812)
22  FrontBoardServices            	0x00000001bc422300 __94-[FBSWorkspaceScenesClient _queue_updateScene:withSettings:diff:transitionContext:completion:]_block_invoke_2 + 152 (FBSWorkspaceScenesClient.m:692)
23  FrontBoardServices            	0x00000001bc42219c -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 168 (FBSWorkspace.m:411)
24  FrontBoardServices            	0x00000001bc4220b8 __94-[FBSWorkspaceScenesClient _queue_updateScene:withSettings:diff:transitionContext:completion:]_block_invoke + 344 (FBSWorkspaceScenesClient.m:691)
25  libdispatch.dylib             	0x00000001ac141300 _dispatch_client_callout + 20 (object.m:561)
26  libdispatch.dylib             	0x00000001ac144d48 _dispatch_block_invoke_direct + 284 (queue.c:496)
27  FrontBoardServices            	0x00000001bc41e520 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 52 (FBSSerialQueue.m:285)
28  FrontBoardServices            	0x00000001bc41e4a0 -[FBSMainRunLoopSerialQueue _targetQueue_performNextIfPossible] + 240 (FBSSerialQueue.m:309)
29  FrontBoardServices            	0x00000001bc41e378 -[FBSMainRunLoopSerialQueue _performNextFromRunLoopSource] + 28 (FBSSerialQueue.m:322)
30  CoreFoundation                	0x00000001a41bb31c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28 (CFRunLoop.c:1957)
31  CoreFoundation                	0x00000001a41ba598 __CFRunLoopDoSource0 + 176 (CFRunLoop.c:2001)
32  CoreFoundation                	0x00000001a41b8d4c __CFRunLoopDoSources0 + 244 (CFRunLoop.c:2038)
33  CoreFoundation                	0x00000001a41b7a88 __CFRunLoopRun + 828 (CFRunLoop.c:2955)
34  CoreFoundation                	0x00000001a41b7668 CFRunLoopRunSpecific + 608 (CFRunLoop.c:3420)
35  GraphicsServices              	0x00000001e75825ec GSEventRunModal + 164 (GSEvent.c:2196)
36  UIKitCore                     	0x00000001a65d42b4 -[UIApplication _run] + 888 (UIApplication.m:3685)
37  UIKitCore                     	0x00000001a65d38f0 UIApplicationMain + 340 (UIApplication.m:5270)
38  UIKitCore                     	0x00000001a67fd9c8 UIApplicationMain(_:_:_:_:) + 104 (UIKit.swift:539)
39  App                    	        0x0000000102508f60 specialized static UIApplicationDelegate.main() + 28 `

**Comment by boehlerlukas** [comment] 2023-11-20 13:14
@kkarakamis Thanks a lot for sharing! We will have another deep look into this!

**Comment by boehlerlukas** [comment] 2023-11-29 13:40
@kkarakamis thanks a lot for providing the crash logs. This should be catched in v13.0.0 (will be released later today). Happy to hear back from you.

**Comment by kkarakamis** [comment] 2023-12-07 12:50
It happens both simulator & devices. Nothing special, but it happens in sending background & foreground phases more often. I work full-time and experience this issue on my own 2-3 times a week.
We are not doing so much with gleap. We are initialising & hiding feedback button in AppDelegate.
Shake to open is active. And also we have a navbar button in the settings which leads to Gleap.

**Comment by boehlerlukas** [comment] 2023-12-07 14:24
@kkarakamis thanks a lot for the additional input - i will try to stress more on it to see if i somehow manage to reproduce it - especially backgroung / foreground phases might be helpful to test.

**Comment by boehlerlukas** [comment] 2023-12-18 10:42
@kkarakamis we are having a super hard time reproducing the issue - i did also try to automatically reproduce by running some automated UI tests for some hours without any success so far.
What iOS versions are you testing on?

**Comment by kkarakamis** [comment] 2023-12-18 11:26
<img width="241" alt="Screenshot 2023-12-18 at 14 24 59" src="https://github.com/GleapSDK/Gleap-iOS-SDK/assets/32245278/135af5d0-4769-4f08-b4ed-34768741abe9">
Sorry to hear that. Here is the distribution for last 2 weeks.
All of the devices & iOS versions 😄

**Comment by boehlerlukas** [comment] 2023-12-18 11:28
@kkarakamis Thanks a lot for sharing! Is there anything else you could think of that might trigger that issue reliably? Being able to reproduce it reliably would be awesome.

**Comment by kkarakamis** [comment] 2023-12-18 11:45
@boehlerlukas 
Sorry, I can't think of anything else.
It can happen at any time. Whether orientation lock is on or not. It doesn't matter on simulator or device.
We use "shake to open".
In the simulator, we sometimes get crashes even without any shake or orientation change. Should that function run without any orientation changes?

**Comment by boehlerlukas** [comment] 2023-12-18 12:29
No worries, thanks a lot for your input so far. We will def. keep on trying to find a way to reproduce the issue - the shake gesture might also be a good guess for reproduction.

**Comment by boehlerlukas** [comment] 2024-10-08 17:51
@kkarakamis could you check with v14.0.2 of the SDK? We really couldn't reproduce the issue once in any environment.

**Closed** 2024-10-21 19:06 UTC
